export const START_LOADING = "AUTH_START_LOADING";
export const END_LOADING = "AUTH_END_LOADING";
export const AUTHENTICATE_USER = "AUTH_AUTHENTICATE_USER";
export const SHOW_ERROR = "AUTH_SHOW_ERROR";
export const SHOW_SUCCESS = "AUTH_SHOW_SUCCESS";
export const RESET_ALERT = "AUTH_RESET_ALERT";
export const LOGOUT_USER = "AUTH_LOGOUT_USER";
export const FORGOT_USER = "AUTH_FORGOT_USER";
