export const SHOW_CYCLE_OPEN = "OPEN_CYCLE_POPUP";
export const SHOW_CYCLE_CLOSE = "CLOSE_CYCLE_POPUP";
export const SHOW_MORTALITY_OPEN = "OPEN_MORTALITY_POPUP";
export const SHOW_MORTALITY_CLOSE = "CLOSE_MORTALITY_POPUP";
export const SHOW_SUCCESS = "SHOW_SUCCESS";
export const SHOW_ERROR = "SHOW_ERROR";
