export const START_LOADING = "SETTING_START_LOADING";
export const END_LOADING = "SETTING_END_LOADING";
export const UPDATE_FEEDBACK = "SETTING_UPDATE_FEEDBACK";
export const SHOW_ERROR = "SETTING_SHOW_ERROR";
export const SHOW_SUCCESS = "SETTING_SHOW_SUCCESS";
export const RESET_ALERT = "SETTING_RESET_ALERT";
