version: 1
frontend:
  phases:
    install:
      runtime-versions:
         nodejs: 16
         
    preBuild:
      commands:
        - npm install env-cmd
        - npm install
    build:
      commands:
        - echo "running on staging" 
        - npm run build:staging 
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*